Portfolio: add a contact form and finish the mobile version
ShiroYaksha90/Mobile-first pull request #5
Opened 2022-11-01 16:25 UTC by ShiroYaksha90

Update the HTML file by adding a contact form.
Update the CSS file by styling the newly added elements.

2022-11-01 17:20 UTC, Owusu-Desmond requested changes
Hi @ShiroYaksha90 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/dxbPGFv7tSK3e/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the set up the project ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._
- [x] Please, next time make sure your commit messages are summarised and descriptive. But as you can see, you have a long commit message with is not summarised. You can read more about it [here](https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/) :pray:

- [ ] Please kindly make sure your project is responsive on mobile screens. Now your project has a horizontal scroll on mobile screens greater than `375px`. You can see this from the screenshot below. :pray:
  
  [Screencast from 11-01-2022 04:40:25 PM.webm](https://user-images.githubusercontent.com/92303891/199288871-29c5cead-eb82-43fe-8b8d-86a9d8c82f07.webm)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 17:20 UTC, Owusu-Desmond commented on index.html
> +
- [ ] Please why don't you use `hX` tag for the content `I'm always interested in hearing about new projects, so if you'd like to chat please get in touch.` instead of using `header` since the header suppose to use for the whole page header?

2022-11-01 17:20 UTC, Owusu-Desmond commented on styles.css
> +}
- [ ] Why don't you give your button CSS property like `cursor: pointer` to make the cursor change on hover?

2022-11-01 17:20 UTC, Owusu-Desmond commented on index.html
> +      </form>
- [ ] Your form is not submitting on submit, Please kindly make sure you fix this.

  [Screencast from 11-01-2022 05:18:55 PM.webm](https://user-images.githubusercontent.com/92303891/199296129-b2bbbe93-b38a-4a86-95bd-d1c1bf63815d.webm)

2022-11-01 18:56 UTC, frank1738 approved these changes
Hi @ShiroYaksha90 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay
✅ Form submission working properly 👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 23:52 UTC, merged

2022-11-08 08:36 UTC, Olamarx reviewed
Hi @ShiroYaksha90, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is supposed to be done in pair-programming. If it was a solo project, I would have approved it but unfortunately, it is pair programming and the commits of your partner(s) are needed to approve it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._